### ISSUE TITLE
No remarkable tab

### ISSUE THREAD

**Issue by obelixA** [jamesf91/RemarkableSync#7]
Hi
the installer runs w/o issues, but neither OneNote nor OneNote for Windows 10 has a remarkable tab.

any ideas why?

best
Obelix

**Comment by jamesf91** [comment]
Hi @obelixA , 3rd party addins are not supports in OneNote for Windows 10. 
For normal OneNote, make sure you have installed the correct 32/64 bit matching your OneNote version
![snippet1](https://user-images.githubusercontent.com/2037620/122549725-288d4f80-d076-11eb-861e-94e956ccd547.JPG)

**Comment by obelixA** [comment]
ok - never thought a 64 bit windows is running a 32 bit office :-)
but after inserting the keys is still does not work...

Error getting notebook structure from reMarkable.
Unable to get SSH password from config store

but the settings ware made for cloud and the scrip keys...

**Comment by obelixA** [comment]
settings always switch back to ssh

**Comment by jamesf91** [comment]
Yeah, both of them are known issues I just fixed in #8 . Publishing a new release now

**Comment by jamesf91** [comment]
New [release 2.0.2](https://github.com/jamesf91/RemarkableSync/releases) should fix both issues

**Comment by obelixA** [comment]
not quite fixed ;-)

Error getting notebook structure from reMarkable.
Unable to get SSH password from config store


and then USB SSH is selected again and the password and keys are vanished

**Comment by jamesf91** [comment]
Umm, sounds like the old behavior. I wonder if the x86 installer didn't rebuild correctly. Let me check again tonight.

**Comment by obelixA** [comment]
I did an uninstall before reinstalling new version. Also did an uninstall of 2.0.2 and reinstalled. Now it's "working".
is there a way to get the notes as freehand? digitizing is crap if you have a handwriting like mine :-D

**Comment by jamesf91** [comment]
Sorry I'm not planning on any major new feature in the near future due to other commitments.  

Feel free to fork the repo and add a module to the converter to convert to image instead of text. reMarkable cloud only provides stroke definitions of each page so getting freehand notes will involve converting strokes to some sort of image. Unfortunately I don't have a lot of knowledge in this area.

**Comment by Alkoch33** [comment]
> Hi @obelixA , 3rd party addins are not supports in OneNote for Windows 10. For normal OneNote, make sure you have installed the correct 32/64 bit matching your OneNote version ![snippet1](https://user-images.githubusercontent.com/2037620/122549725-288d4f80-d076-11eb-861e-94e956ccd547.JPG)

Where does it ask you to select either 32 or 64 bit?  I run the msi installer and it just goes through - I only ever got prompted for installation location.  I'm sure I am missing something but I'm not sure what.  I didn't see anything other than the msi for the installation.

**Comment by mojatt** [comment]
> Hi @obelixA , 3rd party addins are not supports in OneNote for Windows 10. 

Really interested to use this but I'm running Windows 10. Is there a workaround to get this going in Windows 10 for OneNote?
